package com.example.quoteapp.lifequoteRepository

class LifeRepo {
    fun setLifeData(): ArrayList<LifequotesData> {
        val text=ArrayList<LifequotesData>()
        text.add(LifequotesData("\"Spread love everywhere you go. Let no one ever come to you without leaving happier.\" -Mother Teresa"))
        text.add(LifequotesData("\"When you reach the end of your rope, tie a knot in it and hang on.\" -Franklin D. Roosevelt"))
        text.add(LifequotesData(" \"Always remember that you are absolutely unique. Just like everyone else.\" -Margaret Mead"))
        text.add(LifequotesData("\"Don't judge each day by the harvest you reap but by the seeds that you plant.\" -Robert Louis Stevenson"))
        text.add(LifequotesData("\"The future belongs to those who believe in the beauty of their dreams.\" -Eleanor Roosevelt"))
        text.add(LifequotesData(" \"Tell me and I forget. Teach me and I remember. Involve me and I learn.\" -Benjamin Franklin"))
        text.add(LifequotesData(" \"The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.\" -Helen Keller"))
        text.add(LifequotesData("\"It is during our darkest moments that we must focus to see the light.\" -Aristotle"))
        text.add(LifequotesData("\"Whoever is happy will make others happy too.\" -Anne Frank"))
        text.add(LifequotesData(" \"Do not go where the path may lead, go instead where there is no path and leave a trail.\" -Ralph Waldo Emerson"))
        text.add(LifequotesData("\"If life were predictable it would cease to be life and be without flavor.\" -Eleanor Roosevelt"))
        text.add(LifequotesData("\"In the end, it's not the years in your life that count. It's the life in your years.\" -Abraham Lincoln"))
        text.add(LifequotesData("\"Life is a succession of lessons which must be lived to be understood.\" -Ralph Waldo Emerson"))
        text.add(LifequotesData("\"You will face many defeats in life, but never let yourself be defeated.\" -Maya Angelou"))
        text.add(LifequotesData("\"Never let thef] fear of striking out keep you from playing thgae me.\" -Babe Ruth"))
        text.add(LifequotesData("\"Life is never fair, and perhaps it is a good thing for most of us that it is not.\" -Oscar Wilde"))
        text.add(LifequotesData("\"The only impossible journey is the one you never begin.\" -Tony Robbins"))
        text.add(LifequotesData("\"In this life we cannot do great things. We can only do small things with great love.\" -Mother Teresa"))
        text.add(LifequotesData("\"Only a life lived for others is a life worthwhile.\" -Albert Einstein"))
        text.add(LifequotesData(" \"The purpose of our lives is to be happy.\" -Dalai Lam"))
        text.add(LifequotesData(" \"Life is what happens when you're busy making other plans.\" -John Lennon"))
        text.add(LifequotesData(" \"You only live once, but if you do it right, once is enough.\" -Mae West"))
        text.add(LifequotesData("\"Live in the sunshine, swim the sea, drink the wild air.\" -Ralph Waldo Emerson"))
        text.add(LifequotesData("\"Go confidently in the direction of your dreams! Live the life you've imagined.\" -Henry David Thoreau"))
        text.add(LifequotesData("\"The greatest glory in living lies not in never falling, but in rising every time we fall.\" -Nelson Mandela"))
        text.add(LifequotesData("\"Life is really simple, but we insist on making it complicated.\" -Confucius"))
        text.add(LifequotesData("\"May you live all the days of your life.\" -Jonathan Swift"))
        text.add(LifequotesData("\"Life itself is the most wonderful fairy tale.\" -Hans Christian Andersen"))
        text.add(LifequotesData("\"Do not let making a living prevent you from making a life.\" -John Wooden"))
        text.add(LifequotesData("\"Life is ours to be spent, not to be saved.\" -D. H. Lawrence"))
        text.add(LifequotesData("\"Keep smiling, because life is a beautiful thing and there's so much to smile about.\" -Marilyn Monroe"))
        text.add(LifequotesData("\"Life is a long lesson in humility.\" -James M. Barrie"))
        text.add(LifequotesData("\"In three words I can sum up everything I've learned about life: it goes on.\" -Robert Frost"))
        text.add(LifequotesData(" \"Love the life you live. Live the life you love.\" -Bob Marley"))
        text.add(LifequotesData("\"Life is either a daring adventure or nothing at all.\" -Helen Keller"))
        text.add(LifequotesData("\"You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.\" -Dr. Seuss"))
        text.add(LifequotesData(" \"Life is made of ever so many partings welded together.\" -Charles Dickens"))
        text.add(LifequotesData("\"Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma — which is living with the results of other people's thinking.\" -Steve Jobs"))
        text.add(LifequotesData("\"Life is trying things to see if they work.\" -Ray Bradbury"))
        text.add(LifequotesData("\"Many of life's failures are people who did not realize how close they were to success when they gave up.\" -Thomas A. Edison"))
        text.add(LifequotesData("\"The secret of success is to do the common thing uncommonly well.\" -John D. Rockefeller Jr."))
        text.add(LifequotesData("\"I find that the harder I work, the more luck I seem to have.\" -Thomas Jefferson"))
        text.add(LifequotesData("\"Success is not final; failure is not fatal: It is the courage to continue that counts.\" -Winston S. Churchill"))
        text.add(LifequotesData(" \"The way to get started is to quit talking and begin doing.\" -Walt Disney"))
        text.add(LifequotesData(" \"Don't be distracted by criticism. Remember — the only taste of success some people get is to take a bite out of you.\" -Zig Ziglar"))
        text.add(LifequotesData("\"Success usually comes to those who are too busy to be looking for it.\" -Henry David Thoreau"))
        return text
    }

}