package com.example.quoteapp.GymRepository

import com.example.quoteapp.FunnyRepository.FunnyquotesData

class GymRepo {
    fun setGymData():List<GymquotesData>{
        val text=ArrayList<GymquotesData>()
        text.add(GymquotesData("“I hated every minute of training, but I said, ‘Don’t quit. Suffer now and live the rest of your life as a champion.” – Muhammad Ali"))
        text.add(GymquotesData("“We are what we repeatedly do. Excellence then is not an act but a habit.” –Aristotele"))
        text.add(GymquotesData("“The body achieves what the mind believes.” – Napoleon Hill"))
        text.add(GymquotesData("“The hard days are the best because that’s when champions are made, so if you push through, you can push through anything.” – Dana Vollmer"))
        text.add(GymquotesData("“If you don’t find the time, if you don’t do the work, you don’t get the results.” – Arnold Schwarzenegger"))
        text.add(GymquotesData("“Dead last finish is greater than did not finish, which trumps did not start.” — Unknown"))
        text.add(GymquotesData("“Push harder than yesterday if you want a different tomorrow.” – Vincent Williams Sr."))
        text.add(GymquotesData("“The real workout starts when you want to stop.” – Ronnie Coleman"))
        text.add(GymquotesData("“Take care of your body. It’s the only place you have to live.” — Jim Rohn"))
        text.add(GymquotesData("“I’ve failed over and over again in my life and that is why I succeed.” – Michael Jordan"))
        text.add(GymquotesData("“Once you are exercising regularly, the hardest thing is to stop it.” – Erin Gray"))
        text.add(GymquotesData("“The secret of getting ahead is getting started.” — Mark Twain"))
        text.add(GymquotesData("“Exercise should be regarded as tribute to the heart” – Gene Tunney"))
        text.add(GymquotesData("“You’re going to have to let it hurt. Let it suck. The harder you work, the better you will look. Your appearance isn’t parallel to how heavy you lift, it’s parallel to how hard you work.” –Joe Mangianello"))
        text.add(GymquotesData("“Most people fail, not because of lack of desire, but, because of lack of commitment.” –Vince Lombardi"))
        text.add(GymquotesData("“You miss one hundred percent of the shots you don’t take.” – Wayne Gretzky"))
        text.add(GymquotesData("“If something stands between you and your success, move it. Never be denied.” – Dwayne “The Rock” Johnson"))
        text.add(GymquotesData("“Just believe in yourself. Even if you don’t, just pretend that you do and at some point, you will.” – Venus Williams"))
        text.add(GymquotesData("“The harder you work and the more prepared you are for something, you’re going to be able to persevere through anything.” – Carli Lloyd"))
        text.add(GymquotesData("“Enduring means accepting. Accepting things as they are and not as you would wish them to be, and then looking ahead, not behind.” – Rafael Nadal"))
        text.add(GymquotesData("“If you want something you’ve never had, you must be willing to do something you’ve never done.” – Thomas Jefferson"))
        text.add(GymquotesData("“The resistance that you fight physically in the gym and the resistance that you fight in life can only build a strong character.” – Arnold Schwarzenegger"))
        text.add(GymquotesData("“Continuous improvement is better than delayed perfection.” – Mark Twain"))
        text.add(GymquotesData("“Once you learn to quit, it becomes a habit.” – Vince Lombardi"))
        text.add(GymquotesData("“It’s hard to beat a person who never gives up.” – Babe Ruth"))
        text.add(GymquotesData("“Do something today that your future self will thank you for.” — Sean Patrick Flanery"))
        text.add(GymquotesData("“Think of your workouts as important meetings you schedule with yourself. Bosses don’t cancel” – Unknown"))
        text.add(GymquotesData("“Workout till you feel that pain and soreness in muscles. This one is good pain. No pain, no gain.” – Invajy"))
        text.add(GymquotesData("“I don’t count my sit-ups. I only start counting when it starts hurting because they’re the only ones that count.”–Muhammad Ali"))
        text.add(GymquotesData("“Strength does not come from physical capacity. It comes from an indomitable will” –Mahatma Gandhi"))
        text.add(GymquotesData("“The last three or four reps is what makes the muscle grow. This area of pain divides a champion from someone who is not a champion.” – Arnold Schwarzenegger"))
        text.add(GymquotesData("“If you fail to prepare, you’re prepared to fail.” – Mark Spitz"))
        text.add(GymquotesData("“A champion is someone who gets up when they can’t.” – Jack Dempsey"))
        text.add(GymquotesData("“When you have a clear vision of your goal, it’s easier to take the first step toward it.” – LL Cool J"))
        text.add(GymquotesData("“When I feel tired, I just think about how great I will feel once I finally reach my goal.” – Michael Phelps"))
        text.add(GymquotesData("“You have to think about it before you can do it. The mind is what makes it all possible.” – Kai Greene"))
        text.add(GymquotesData("“Don’t be afraid of failure. This is the way to succeed.” – LeBron James"))
        text.add(GymquotesData("“You should never stay at the same level. Always push yourself to the next.” – Marnelli Dimzon"))
        text.add(GymquotesData("“You did not wake up today to be mediocre.” – Robin Arzon"))
        text.add(GymquotesData("“If you want to be the best, you have to do things other people aren’t willing to do.” – Michael Phelps"))
        text.add(GymquotesData("“If you are not pissed off for greatness, that just means you’re okay with being mediocre.” – Ray Lewis"))
        text.add(GymquotesData("“Don’t dream of winning. Train for it!” – Mo Farah"))
        text.add(GymquotesData("“Most people give you right before the big break comes, don’t let that person be you.” – Michael Boyle"))
        text.add(GymquotesData("“Keep listening to your body. It will tell you when something is not okay.” – Emily Infeld"))
        return text
    }
}