package com.example.quoteapp.FunnyRepository

class FunnyRepo {
    fun setFunnyData():List<FunnyquotesData>{
        val text=ArrayList<FunnyquotesData>()
        text.add(FunnyquotesData("“You know you’ve reached middle age when you’re cautioned to slow down by your doctor, instead of by the police.” — Joan Rivers"))
        text.add(FunnyquotesData("“Money cannot buy health, but I'd settle for a diamond-studded wheelchair.” — Dorothy Parker"))
        text.add(FunnyquotesData("“Before you criticize someone, you should walk a mile in their shoes. That way when you criticize them, you are a mile away from them and you have their shoes.” — Jack Handey"))
        text.add(FunnyquotesData("“I'm sick of following my dreams, man. I'm just going to ask where they're going and hook up with ’em later.\" — Mitch Hedberg"))
        text.add(FunnyquotesData("“Never follow anyone else’s path. Unless you’re in the woods and you’re lost and you see a path. Then by all means follow that path.” — Ellen DeGeneres"))
        text.add(FunnyquotesData("“Outside of a dog, a book is man’s best friend. Inside of a dog, it’s too dark to read.” — Groucho Marx"))
        text.add(FunnyquotesData("“I like freedom. I wake up in the morning and say, ‘I don’t know, should I have a popsicle or a donut?’ You know, who knows?” — Oscar Nunez"))
        text.add(FunnyquotesData("“Someone asked me, if I were stranded on a desert island what book would I bring: ‘How to Build a Boat.’” — Steven Wright"))
        text.add(FunnyquotesData("“Common sense is like deodorant. The people who need it most never use it.” — Anonymous"))
        text.add(FunnyquotesData("“If I’m not back in five minutes, just wait longer.” — Ace Ventura (Jim Carrey),  Ace Ventura: Pet Detective"))
        text.add(FunnyquotesData("“Why do they call it rush hour when nothing moves?” — Robin Williams"))
        text.add(FunnyquotesData("“The only thing that separates us from the animals is our ability to accessorize.” — Claire Belcher"))
        text.add(FunnyquotesData("“A good rule to remember for life is that when it comes to plastic surgery and sushi, never be attracted by a bargain.” — Graham Norton"))
        text.add(FunnyquotesData("“As you get older, three things happen. The first is your memory goes, and I can’t remember the other two.” — Sir Norman Wisdom"))
        text.add(FunnyquotesData("“You know you’re getting old when you stoop to tie your shoelaces and wonder what else you could do while you’re down there.” — George Burns"))
        text.add(FunnyquotesData("Any man who can drive safely while kissing a pretty girl is simply not giving the kiss the attention it deserves.\" — Albert Einstein"))
        text.add(FunnyquotesData("“People say, ‘But Betty, Facebook is a great way to connect with old friends.’ Well, at my age, if I want to connect with old friends I need a Ouija board.” — Betty White"))
        text.add(FunnyquotesData("“Accept who you are. Unless you’re a serial killer.” — Ellen DeGeneres"))
        text.add(FunnyquotesData("“My ability to turn good news into anxiety is rivaled only by my ability to turn anxiety into chin acne.” — Tina Fey,  Bossypants"))
        text.add(FunnyquotesData("“Here’s some advice: At a job interview, tell them you’re willing to give 110 percent. Unless the job is a statistician.” — Adam Gropman"))
        text.add(FunnyquotesData("“I used to sell furniture for a living. The trouble was, it was my own.” — Les Dawson"))
        text.add(FunnyquotesData("“I am a friend of the working man, and I would rather be his friend, than be one.” — Clarence Darrow"))
        text.add(FunnyquotesData("“The best way to appreciate your job is to imagine yourself without one.” — Oscar Wilde"))
        text.add(FunnyquotesData("“If my boss knew how unproductive I am on Fridays, he wouldn’t want me here either.” — James Johnson"))
        text.add(FunnyquotesData("“Every Friday, I like to high five myself for getting through another week on little more than caffeine, willpower, and inappropriate humor.” —Nanea Hoffman"))
        text.add(FunnyquotesData("“Never put off till tomorrow what you can do the day after tomorrow just as well.” — Mark Twain"))
        text.add(FunnyquotesData("“Today’s goals: Coffee and kindness. Maybe two coffees, and then kindness.” — Nanea Hoffman"))
        text.add(FunnyquotesData("“Trying is the first step toward failure.” — Homer Simpson,  The Simpsons"))
        text.add(FunnyquotesData("“People say nothing is impossible, but I do nothing every day.” — Winnie the Pooh"))
        text.add(FunnyquotesData("“Be the person that when your feet touch the floor in the morning the devil says, “Awe sh*t, they’re up”. — Dwayne Johnson"))
        text.add(FunnyquotesData("“My therapist says I'm afraid of success. I guess I could understand that, because after all, fulfilling my potential would really cut into my sitting-around time.” — Maria Bamford"))
        text.add(FunnyquotesData("“I wake up every morning at nine and grab for the morning paper. Then I look at the obituary page. If my name is not on it, I get up.” — Benjamin Franklin"))
        text.add(FunnyquotesData("“Clothes make the man. Naked people have little or no influence in society.” — Mark Twain"))
        text.add(FunnyquotesData("“A day without sunshine is like, you know, night.” — Steve Martin"))
        text.add(FunnyquotesData("“I have a lot of growing up to do. I realized that the other day inside my fort.” — Zach Galifianakis"))
        text.add(FunnyquotesData("\"I have the same goal I've had ever since I was a girl. I want to rule the world"))
        text.add(FunnyquotesData("“Anyone who lives within their means suffers from a lack of imagination.” — Oscar Wilde"))
        text.add(FunnyquotesData("Happiness is having a large, loving, caring, close-knit family in another city.” — George Burns"))
        text.add(FunnyquotesData("“Spend some time this weekend on home improvement; improve your attitude toward your family.” — Bo Bennett"))
        text.add(FunnyquotesData("“I want my children to have all the things I couldn't afford. Then I want to move in with them.” — Phyllis Diller"))
        text.add(FunnyquotesData("“I’d like to have a kid, but I’m not sure I’m ready to spend 10 years of my life constantly asking someone where his shoes are.” — Damien Fahey"))
        text.add(FunnyquotesData("“I’m sure wherever my Dad is, he’s looking down on us. He’s not dead, just very condescending.” — Jack Whitehall"))
        text.add(FunnyquotesData("“From the ages of eight to 18, me and my family moved around a lot. Mostly we would just stretch, but occasionally one of us would actually get up to go to the fridge.” — Jarod Kintz"))
        text.add(FunnyquotesData("“Good parenting means investing in your child's future, which is why I am saving to buy mine a hoverboard someday.” —Lin-Manuel Miranda"))
        text.add(FunnyquotesData("\"If love is the answer, then could you rephrase the question?” — Lily Tomlin"))
        text.add(FunnyquotesData("\"If I get married, I want to be very married.\" — Audrey Hepburn"))
        return text
    }
}