package com.example.quoteapp.travelRepository

import com.example.quoteapp.GymRepository.GymquotesData

class TravelRepo {
    fun setTravelData():List<TravelquotesData>{
        val text=ArrayList<TravelquotesData>()
        text.add(TravelquotesData("“Not all those who wander are lost.” – J. R. R. Tolkien"))
        text.add(TravelquotesData("“The soul of the journey is liberty, perfect liberty, to think, feel, do just as one pleases.” William Hazlitt"))
        text.add(TravelquotesData("“For always roaming with a hungry heart, much have I seen and known.” Alfred Tennyson"))
        text.add(TravelquotesData("“Don’t tell me how educated you are, tell me how much you travelled.”  The Prophet Mohamed"))
        text.add(TravelquotesData("“A journey is like marriage. The certain way to be wrong is to think you control it.”  John Steinbeck"))
        text.add(TravelquotesData("“A ship in a harbor is safe, but it not what ships are built for.” – John A. Shedd."))
        text.add(TravelquotesData("“Bizarre travel plans are dancing lessons from God.” – Kurt Vonnegut.  "))
        text.add(TravelquotesData("“Remember that happiness is a way of travel – not a destination.” – Roy M. Goodman"))
        text.add(TravelquotesData("“Traveling – it leaves you speechless, then turns you into a storyteller.” – Ibn Battuta"))
        text.add(TravelquotesData("“Travel makes one modest, you see what a tiny place you occupy in the world.”  – Gustave Flaubert"))
        text.add(TravelquotesData("“Travel is fatal to prejudice, bigotry, and narrow-mindedness.”  Mark Twain"))
        text.add(TravelquotesData("“One’s destination is never a place, but a new way of seeing things.”  Henry Miller"))
        text.add(TravelquotesData("“Live your life by a compass not a clock.” – Stephen Covey"))
        text.add(TravelquotesData("“You know more of a road by having travelled it than by all the conjectures and descriptions in the world.” –  William Hazlitt"))
        text.add(TravelquotesData("“People travel to faraway places to watch, in fascination, the kind of people they ignore at home.” –   Dagobert David Runes"))
        text.add(TravelquotesData("“Not until we are lost do we begin to understand ourselves.”  – Henry David Thoreau"))
        text.add(TravelquotesData("“Two roads diverged in a wood and I – I took the one less travelled by.”  Robert Lee Frost"))
        text.add(TravelquotesData("“Without new experiences, something inside of us sleeps. The sleeper must awaken.” – Frank Herbert"))
        text.add(TravelquotesData("“All journeys have secret destinations of which the traveller is unaware.” – Martin Buber."))
        text.add(TravelquotesData("“The journey of a thousand miles begins with a single step.” – Lao Tzu"))
        text.add(TravelquotesData("“Travel doesn’t become adventure until you leave yourself behind.” – Marty Rubin"))
        text.add(TravelquotesData(" “I’m in love with cities I’ve never been to and people I’ve never met.” – Melody Truong"))
        text.add(TravelquotesData("“If you reject the food, ignore the customs, fear the religion and avoid the people, you might better stay home.” – James Michener"))
        text.add(TravelquotesData("“There are no foreign lands. It is the traveler only who is foreign.” — Robert Louis Stevenson"))
        text.add(TravelquotesData("“The more I traveled the more I realized that fear makes strangers of people who should be friends.” – Shirley MacLaine"))
        text.add(TravelquotesData("“Only those who risk going too far can possibly find out how far they can go.” -T.S Eliot"))
        text.add(TravelquotesData(" “I am not the same, having seen the moon shine on the other side of the world.” -Mary Anne Radmacher"))
        text.add(TravelquotesData("“Travel and change of place impart new vigor to the mind.” -Seneca"))
        text.add(TravelquotesData(" “Man cannot discover new oceans unless he has the courage to lose sight of the shore.” – Andre Gide"))
        text.add(TravelquotesData("“Live life with no excuses, travel with no regret” –Oscar Wilde"))
        text.add(TravelquotesData("“You must go on adventures to find out where you truly belong.” -Sue Fitzmaurice"))
        text.add(TravelquotesData("“Live, travel, adventure, bless, and don’t be sorry.” – Jack Kerouac"))
        text.add(TravelquotesData("“I take to the open road, healthy, free, the world before me.” – Walt Whitman"))
        text.add(TravelquotesData("“Two roads diverged in a wood, and I – I took the one less traveled by.”-Robert Frost"))
        text.add(TravelquotesData("”Nothing behind me, everything ahead of me, as is ever so on the road.” — Jack Kerouac"))
        text.add(TravelquotesData("“The man who goes alone can start today; but he who travels with another must wait till that other is ready.” – Henry David Thoreau"))
        text.add(TravelquotesData("“I have found out that there ain’t no surer way to find out whether you like people or hate them than to travel with them”. – Mark Twain"))
        text.add(TravelquotesData("“It is better to travel well than to arrive.” —Buddha"))
        text.add(TravelquotesData("“Go, fly, roam, travel, voyage, explore, journey, discover, adventure.”"))
        text.add(TravelquotesData("“Travel is never a matter of money but of courage.” – Paolo Coelho"))
        text.add(TravelquotesData("“I travel not to go anywhere, but to go. I travel for travel’s sake. The great affair is to move.” – Robert Louis Stevenson"))
        text.add(TravelquotesData("“Traveling – it leaves you speechless, then turns you into a storyteller.” – Ibn Battuta"))
        text.add(TravelquotesData(" “People don’t take trips, trips take people.” – John Steinbeck"))
        text.add(TravelquotesData(" “Once a year, go someplace you’ve never been before.” – Dalai Lama"))
        return text
    }
}